# Generated by Django 3.2.6 on 2021-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_xd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XD',
        ),
    ]
