# Generated by Django 3.2.6 on 2021-09-16 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 18, 47, 8, 382536)),
        ),
    ]
